services:
  frontend:
    image: ${FRONTEND_IMAGE}
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 20s
        failure_action: rollback
        order: start-first
        monitor: 60s
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.http.routers.signage-frontend.rule=Host(`signage.cemalturkcan.com`)
        - traefik.http.routers.signage-frontend.entrypoints=websecure
        - traefik.http.routers.signage-frontend.tls.certresolver=main
        - traefik.http.routers.signage-frontend.priority=1
        - traefik.http.services.signage-frontend.loadbalancer.server.port=80
