export const COMMAND_ERROR_CODES = {
  INVALID_JSON: 'INVALID_JSON',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  UNSUPPORTED_COMMAND: 'UNSUPPORTED_COMMAND',
  NO_HANDLER: 'NO_HANDLER',
  SCREENSHOT_FAILED: 'SCREENSHOT_FAILED',
  EXECUTION_ERROR: 'EXECUTION_ERROR',
} as const

export type CommandErrorCode = (typeof COMMAND_ERROR_CODES)[keyof typeof COMMAND_ERROR_CODES]
