listener 1883
protocol mqtt

listener 9001
protocol websockets

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type information

allow_anonymous false
plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json
plugin_opt_password_env_var MOSQUITTO_DYNSEC_PASSWORD
